### ISSUE TITLE
Raw HTML and JS Files for games?

### ISSUE THREAD

**Issue by super-15** [mountain658/mountain658.github.io#5]
Hello, I was wondering if I could get the raw HTML files from the website (all of them) because the ones on the repo don't seem to be working when I put all the necessary ones (at least I think) into a folder. I'm trying to get Moto X3M's raw html and js files.

**Comment by mountain658** [comment]
All the raw files can be found here:
https://github.com/mountain658/mountain658.github.io/tree/main/g/moto-x3m

You can download them here (instead of the entire repo):
https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fmountain658%2Fmountain658.github.io%2Ftree%2Fmain%2Fg%2Fmoto-x3m

I hope it helps!
